console.log('\x1b[1m', '\n\nAleksandar Timic')
console.log('\x1b[34m', '\nSenior Frontend Developer @ Celsius Network Europe')
console.log('email: aleksandartimic@gmail.com')
console.log('business email: aleksandar.timic@celsius.network')
console.log('phone: +381603364567\n\n')
